dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: /home/lpmayos/hd/code/structural-probes/lpmayos_tests/data/en_ewt-ud-sample/
    train_path: en_ewt-ud-train.conllu
    dev_path: en_ewt-ud-dev.conllu
    test_path: en_ewt-ud-test.conllu
  embeddings:
    type: token #{token,subword}
    root: /home/lpmayos/hd/code/structural-probes/lpmayos_tests/data/en_ewt-ud-sample/kg_ctx_embs_ud_owfalse_hid200_snli
    train_path: en_ewt-ud-train.kg-layers.hdf5
    dev_path: en_ewt-ud-dev.kg-layers.hdf5
    test_path: en_ewt-ud-test.kg-layers.hdf5
  batch_size: 10
model:
  hidden_dim: 925 # k&G embedding dim
  #embedding_dim: 1024 # ELMo word embedding dim
  model_type: ELMo-disk # BERT-disk, ELMo-disk, 
  use_disk: True
  model_layer: 0 # BERT-base: {1,...,12}; ELMo: {1,2,3}; K&G: {1}
probe:
  task_signature: word   # word,         word_pair
  task_name: parse-depth   # parse-depth,  parse-distance
  maximum_rank: 128
  psd_parameters: True
  diagonal: False
  params_path: predictor.params
probe_training:
  epochs: 30
  loss: L1
reporting:
  root: /home/lpmayos/hd/code/structural-probes/lpmayos_tests/results/kg_ctx_embs_ud_owfalse_hid200_snli/parse-depth
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
  # For parse-depth, the valid methods are spearmanr, root_acc, write_predictions, and image_examples
  # For parse-distance, the valid methods are spearmanr, uuas, write_predictions, and image_examples
    - spearmanr
    - root_acc
    - write_predictions
    - image_examples
